"""added users relation to tasks

Revision ID: 58eb9a914e41
Revises: 50bd78024054
Create Date: 2025-02-06 13:45:22.580045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58eb9a914e41'
down_revision: Union[str, None] = '50bd78024054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_user_tasks", 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_tasks", type_='foreignkey')

    # ### end Alembic commands ###
