name: social-app

volumes:
  pgdata:
  pgadmin_data:

services:
  nginx:
    image: nginx:1.31.3-alpine
    container_name: nginx
    depends_on:
      - api
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    profiles:
      - production

  api:
    build: .
    container_name: api
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - 8000:8000
    profiles:
      - production

  api-dev:
    build: .
    container_name: api-dev
    command: /app/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./app:/app/app:ro
      - ./alembic:/app/alembic:ro
      - ./alembic.ini:/app/alembic.ini:ro
    ports:
      - 8000:8000
    profiles:
      - development

  postgres:
    image: postgres:17-trixie@sha256:5c855ad7b85e68e48a62f34662853f38b57c1c1d80f3a927ab58034fd6d31c5e
    container_name: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  pgadmin:
    image: dpage/pgadmin4@sha256:40fa840c5bb7c8463957f1255b01283732c2d8c9396a956d180f8e6c296753b3
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "127.0.0.1:5050:80"
